core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from allauth.account import views
from accounts.views import CustomPasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')), 
    path("password/reset/", CustomPasswordResetView.as_view(), name="account_reset_password"),

    path("accounts/login/", views.login, name="account_reset_password_done"),

    path('users/', include('accounts.urls')),
    path('learn/', include('learn.urls')),
    path('', include('professores.urls', namespace="professores")),
    path('', include('cursos.urls')),    

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root= settings.MEDIA_ROOT
                          )

learn/urls.py
from django.urls import path
from . import views

app_name = 'learn'

urlpatterns = [ 
    path('', views.show_progress, name='progress'),
    path('courses/', views.courses, name='courses'),
    path('courses/<str:tag>/', views.courses, name='filtered_courses'),
    path('courses/<int:course_pk>/', views.course_info, name='course_info'),
]

learn/views.py
from taggit.models import Tag

from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user

from cursos.models import Curso, CourseProgress
from cursos.utils import format_hours
from .utils import *



@login_required
def show_progress(request):
    user = get_user(request)
    courses_in_progress = CourseProgress.objects.filter(user=user, status='in_progress')[:3]
    completed_courses = CourseProgress.objects.filter(user=user, status='completed')[:3]

    context =  {
        'courses_in_progress': courses_in_progress,
        'completed_courses': completed_courses,
    }
    return render(request, 'progress.html', context)

@login_required
@csrf_exempt
def courses(request, tag=None, status=None):
    total_courses = 0 
    message = None

    user = request.user  
    title = request.GET.get('titulo')
    status = request.GET.get('status')

    queryset = Curso.objects.all()
    courses_by_progress = CourseProgress.objects.filter(user=user, status=status)

    if status:
        get_paginator(queryset=courses_by_progress, request=request)
        total_courses = calculate_total_courses(queryset=courses_by_progress)

    if tag:
        queryset = queryset.filter(tags__name=tag)
        total_courses = calculate_total_courses(queryset=queryset)

    elif title: 
        queryset = queryset.filter(titulo__icontains=title) 
        get_paginator(queryset=queryset, request=request)
        total_courses = calculate_total_courses(queryset=queryset)
 
        if not queryset.exists():
            message = f'Não há resultados para "{title}"'   
    
    tags = Tag.objects.all()

    context = {
        'courses': queryset,
        'courses_by_progress': courses_by_progress,
        'tags': tags,
        'total_courses': total_courses,
        'message': message,
        'user': user,
    }

    return render(request, 'courses.html', context)

@login_required
def course_info(request, course_pk):    
    course = Curso.objects.get(pk=course_pk)
   
    context = {
        'course': course,
        #'instructor': course.professor,
        'title': course.titulo,
        'description': course.descricao,
        'presentation': course.apresentacao,
        'level': course.nivel,
        'qt_modules': course.qtd_modulos,
        'course_duration': course.duracao_curso
    }
    return render(request, 'course_info.html', context)

learn/templates/courses.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursos</title>
    
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />

    <script src="https://unpkg.com/alpinejs"></script>

    <!-- tippyjs -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tippy.js/6.3.7/tippy.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://unpkg.com/@ryangjchandler/alpine-tooltip@1.2.0/dist/cdn.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="{% static 'learn/css/custom-font.css' %}" >

    <!-- Alpine.js -->
    <script src="https://unpkg.com/alpinejs"></script>	
</head>

<body class="bg-[#F7F7FC]" style="font-family: 'Studio-Feixen' system-ui, -apple-system;">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>

    {% include 'partials/navbar.html' %}

    <main class="mt-20 ml-10 mb-10 w-[1090px]">

        <div class="flex items-center bg-[#05192d] rounded-[4px] justify-space-between p-[50px] pl-6 text-left">
            <div class="box-border bg-no-repeat" >
                <div class="flex-row mb-2">
                    <h1 class="m-0 p-0 text-white text-[24px]">Cursos</h1>
                </div>
                <p class="text-white text-[15px] max-w-[553px] leading-6">Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae illo dolore alias eos eum tenetur doloremque magnam officia ratione incidunt!</p>
            </div>
        </div>

        <div class="pt-5 pb-23">
            <div class="flex items-center justify-space-between gap-[10px]">
                <div class="flex justify-start wrap items-center">
                    <a id="active" href="{% url 'learn:courses' %}" class="w-auto px-2 py-2.5 rounded-md  text-sm text-[#05192D] bg-[#e8e8ee] hover:bg-gray-200/75">
                        <span class="">Todos</span> 
                    </a>
                </div>
                {% for tag in tags %}
                <div class="flex justify-start wrap items-center">
                    <a href="{% url 'learn:filtered_courses' tag.name %}" class="bg-gray-200 text-[#05192D] w-auto px-2 py-2.5 rounded-md  text-sm hover:bg-gray-200/50">
                        <span class="capitalize">{{tag.name}}</span>
                    </a>
                </div>
                {% endfor %}
                </div>

                <div class="pt-6 pb-2 text-sm text-gray-800 font-bold" >
                    {% if not message %}
                        <p>{{ total_courses }} curso{{ total_courses|pluralize }}</p>
                    {% else %}
                        <p>{{ message }}</p>
                    {% endif %}
                </div>                    
        </div>

        {% if courses %}
            <div id="courses">  
                <div class="grid grid-cols-3 gap-3">
                    {% for course, formatted_hours in courses %}
                        <section class="relative bg-white border border-solid mt-4 transition ease-out delay-150 hover:-translate-y-1 duration-300">
                            <a href="" class="">
                                <span class="">
                                    <p class="text-[#aeaeb3] text-[11px] uppercase tracking-widest leading-normal ml-5 mt-5">{{ course.nivel }}</p>
                                    <h2 class="font-medium overflow-hidden text-[#05192D] ml-5 mt-2 text-[18px] leading-6">{{ course.titulo }}</h2>
                                </span>
                                
                                <span>
                                    <p class="inline-block font-normal leading-6 text-[#616e7a] text-sm px-4 py-4 mb-1">{{ course.apresentacao }}</p>
                                    <div class="flex items-center mb-10">
                                        <img class="w-10 h-10 static rounded-full ml-5" src="https://assets.datacamp.com/authors/avatars/000/001/784/original/3.png?1705586441" >
                                        <div class="text-[#616e7a] leading-5 ml-2">
                                            <p class="text-sm">{{ course.professor }}</p>
                                            <p class="text-[12px]">{{ course.professor.specialization }}</p>
                                        </div>
                                    </div>
                                </span>

                                <footer class="border">
                                    <div class="flex items-center justify-between mt-5 ml-5 mr-5 mb-4">
                                        <p class="text-sm text-[#848492]">{{ formatted_hours }}h</p>
                                        <a class="flex items-center cursor-pointer h-9 w-auto border-2 border-[#8288a5] hover:bg-gray-100 rounded-md pl-4 pr-4">
                                            <span class="font-semibold text-sm text-[#05192D] leading-6 m-0 p-0 ">
                                                Iniciar
                                            </span>
                                        </a>
                                    </div>
                                </footer>
                            </a>
                        </section>
                        {% endfor %}
                </div>
            </div>
        {% endif %}
    </main>

</body>
</html>

learn/templates/progress.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursos - Tech</title>

    <script src="https://cdn.tailwindcss.com"></script>
  	<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tippy.js/6.3.7/tippy.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://unpkg.com/@ryangjchandler/alpine-tooltip@1.2.0/dist/cdn.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://unpkg.com/alpinejs"></script>	
    <link rel="stylesheet" href="{% static 'learn/css/custom-font.css' %}">
</head>

<body class="bg-[#F7F7FC]">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>


  <div class="flex">
    {% include 'partials/navbar.html' %}
      <main class="mx-5 my-20 overflow-x-hidden w-[1090px]">
        <div class="flex items-end justify-start w-full border-b-2 border-b-gray-200 cursor-pointer p-0 text-left">
          <button id="btn-in-progress" value="in_progress" class="overflow-visible bg-transparent border-b-4 border-b-black font-semibold p-0 mb-[-3px] mr-4 pb-2 pl-2">
            <span class="leading-6 text-[16px]">Em andamento</span>
          </button>
          
          <button id="btn-completed" value="completed" class="bg-transparent p-0 mb-[-3px] mr-4 pb-2 pl-2">
            <span class="font-normal leading-6 text-[16px]">Completado</span>
          </button>

          <a id="ver-todos" href="{% url 'learn:courses' %}?status=in_progress" class="transition-colors bg-transparent border-medium-none cursor-pointer ml-auto outline-none pb-2 font-semibold text-[14px] leading-6 text-[#0065d1]">
            Ver todos
          </a>
        </div>

        <script>
          document.getElementById('btn-in-progress').addEventListener('click', function() {
            var href = "{% url 'learn:courses' %}?status=" + this.value;
            document.getElementById('ver-todos').setAttribute('href', href);
          });
        
          document.getElementById('btn-completed').addEventListener('click', function() {
            var href = "{% url 'learn:courses' %}?status=" + this.value;
            document.getElementById('ver-todos').setAttribute('href', href);
          });
        </script>
        
        {% if courses_in_progress %}
          <div id="courses-in-progress">  
              <div class="grid grid-cols-3 gap-3">
                  {% for course_in_progress in courses_in_progress %}
                      <section class="relative bg-white border border-solid mt-4 transition ease-out delay-150 hover:-translate-y-1 duration-300">
                          <a href="" class="">
                              <span class="">
                                  <p class="text-[#aeaeb3] text-[11px] uppercase tracking-widest leading-normal ml-5 mt-5">{{ course_in_progress.course.nivel }}</p>
                                  <h2 class="font-medium overflow-hidden text-[#05192D] ml-5 mt-2 text-[18px] leading-6">{{ course_in_progress.course.titulo }}</h2>
                              </span>
                              
                              <span>
                                  <p class="inline-block font-normal leading-6 text-[#616e7a] text-sm px-4 py-4 mb-1">
                                    {{ course_in_progress.course.apresentacao }}
                                  </p>
                                  <div class="flex items-center mb-10">
                                      <img class="w-10 h-10 static rounded-full ml-5" src="https://assets.datacamp.com/authors/avatars/000/001/784/original/3.png?1705586441" >
                                      <div class="text-[#616e7a] leading-5 ml-2">
                                          <p class="text-sm">{{ course_in_progress.course.professor }}</p>
                                          <p class="text-[12px]">{{ course_in_progress.course.professor.specialization }}</p>
                                      </div>
                                  </div>
                              </span>

                              <footer class="border-t">
                                  <div class="flex items-center justify-between mt-5 ml-5 mr-5 mb-4">
                                      <p class="text-sm text-[#848492]">4h</p>
                                      <a class="flex items-center cursor-pointer h-9 w-auto bg-[#03EF62] rounded-md pl-4 pr-4">
                                          <span class="font-semibold text-sm text-[#05192D] leading-6 m-0 p-0 ">
                                              Continuar
                                          </span>
                                      </a>
                                  </div>
                              </footer>
                          </a>
                      </section>  
                  {% endfor %}
              </div>
          </div>
        {% else %}
          <div class="flex items-center justify-center bg-[#e8e8ee] h-[294px] w-screen mt-0 ml-6 border-t-2 border-gray-200 ">
            <span class="text-[#05192D]">Nada no momento.</span>  
            <a href="{% url 'learn:courses' %}" class=" text-[#0065d1] font-extrabold cursor-pointer ml-1">Acesse nossos cursos para iniciar.</a>     
          </div> 
        {% endif %}

          <div id="completed-courses" class="flex items-center justify-center bg-no-repeat border-box">
              <div style="display: grid; column-gap: 16px; grid-template-columns: 1fr 1fr 1fr;">
                  {% if completed_courses %}
                    {% for completed_course in completed_courses %}
                      <div class="flex">
                        <section class="flex-col bg-white border border-solid p-0 mt-4 transition ease-out delay-150 hover:-translate-y-1 duration-300">
                          <a href="" class="flex-col grow">
                            <div>
                              <h2 class="font-semibold overflow-hidden block text-[#05192D] text-center mt-8 text-[18px] leading-6">{{ completed_course.curso.titulo }}</h2>
                            </div>
                            <span class="overflow-ellipsis block font-normal leading-6 text-[#616e7a] text-[14px] px-5 py-5 mb-1">
                              <p>This chapter covers more complex efficiency tips and tricks. You'll learn a few useful built-in modules for writing efficient code and practice using set theory.</p>
                            </span>
                            <div class="flex items-center mb-10">
                      
                            </div>
                            <footer class="flex flex-col items-center justify-between border-t border-solid border-gray-300 cursor-pointer pt-5 pb-3 pl-5 pr-5">
                              <a href="" class="border-2 border-solid border-[#464957] rounded-md pl-6 pr-6 pt-1 pb-1 hover:bg-gray-100">
                                <span class="text-[14px] text-[#05192d] font-medium leading-6 tracking-wide">Replay</span>
                              </a>
                            </footer>
                          </a>
                        </section>
                      </div>
                    {% endfor %}
                  {% else %}
                    <div class="flex items-center justify-center bg-[#e8e8ee] h-[294px] w-screen ml-6 mt-0 border-t-2 border-gray-200 ">
                      <span class="text-[#05192D]">Nada no momento.</span>  
                      <a href="{% url 'learn:courses' %}" class="text-[#0065d1] font-extrabold cursor-pointer ml-1">Acesse nossos cursos para iniciar.</a>     
                    </div> 
                  {% endif %}
              </div> 
          </div>
          <script src="{% static 'learn/js/progress.js' %}"></script>
        </main>
  </div>

</body>
</html>