core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from allauth.account import views
from accounts.views import CustomPasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')), 
    path("password/reset/", CustomPasswordResetView.as_view(), name="account_reset_password"),

    path("accounts/login/", views.login, name="account_reset_password_done"),

    path('users/', include('accounts.urls')),
    path('learn/', include('learn.urls')),
    path('', include('professores.urls', namespace="professores")),
    path('', include('cursos.urls')),    

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root= settings.MEDIA_ROOT
                          )

learn/urls.py
from django.urls import path
from . import views

app_name = 'learn'

urlpatterns = [ 
    path('', views.show_progress, name='progress'),
    path('courses/', views.courses, name='courses'),
    path('courses/<str:tag>/', views.courses, name='filtered_courses'),
    path('courses/<int:course_pk>/', views.course_info, name='course_info'),
]

learn/views.py
from taggit.models import Tag

from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user

from cursos.models import Curso, CourseProgress
from cursos.utils import format_hours
from .utils import *



@login_required
def show_progress(request):
    user = get_user(request)
    courses_in_progress = CourseProgress.objects.filter(user=user, status='in_progress')[:3]
    completed_courses = CourseProgress.objects.filter(user=user, status='completed')[:3]

    context =  {
        'courses_in_progress': courses_in_progress,
        'completed_courses': completed_courses,
    }
    return render(request, 'progress.html', context)

@login_required
@csrf_exempt
def courses(request, tag=None, status=None):
    total_courses = 0 
    message = None

    user = request.user  
    title = request.GET.get('titulo')
    status = request.GET.get('status')

    queryset = Curso.objects.all()
    courses_by_progress = CourseProgress.objects.filter(user=user, status=status)

    if status:
        get_paginator(queryset=courses_by_progress, request=request)
        total_courses = calculate_total_courses(queryset=courses_by_progress)

    if tag:
        queryset = queryset.filter(tags__name=tag)
        total_courses = calculate_total_courses(queryset=queryset)

    elif title: 
        queryset = queryset.filter(titulo__icontains=title) 
        get_paginator(queryset=queryset, request=request)
        total_courses = calculate_total_courses(queryset=queryset)
 
        if not queryset.exists():
            message = f'Não há resultados para "{title}"'   
    
    tags = Tag.objects.all()

    context = {
        'courses': queryset,
        'courses_by_progress': courses_by_progress,
        'tags': tags,
        'total_courses': total_courses,
        'message': message,
        'user': user,
    }

    return render(request, 'courses.html', context)

@login_required
def course_info(request, course_pk):    
    course = Curso.objects.get(pk=course_pk)
   
    context = {
        'course': course,
        #'instructor': course.professor,
        'title': course.titulo,
        'description': course.descricao,
        'presentation': course.apresentacao,
        'level': course.nivel,
        'qt_modules': course.qtd_modulos,
        'course_duration': course.duracao_curso
    }
    return render(request, 'course_info.html', context)

learn/templates/partials/navbar.html
{% load custom_tags %}

<div style="font-family: 'Studio-Feixen' system-ui, -apple-system; ">

  <header class="flex items-center justify-between fixed top-0 w-full h-[54px] bg-white p-4 z-10 shadow" style="font-family: 'Studio-Feixen' system-ui, -apple-system;">
      <h2 class="font-medium text-lg">Tech</h2>

        <div id="nav" class="flex items-center">
          <div class="flex items-center justify-between basis-auto h-[38px] grow-0 bg-[#efeff5] rounded-full">
            <a href="{% url 'learn:progress' %}" class="hover:bg-[#dadadf] hover:rounded-full mt-1.5 mb-1.5 ml-1 cursor-pointer">
              <span class="text-[14px] text-[#05192d] whitespace-nowrap leading-[30px] ml-4 mr-4">Progresso</span>
            </a>
            <a href="{% url 'learn:courses' %}" class="hover:bg-[#dadadf] hover:rounded-full mt-1.5 mb-1.5 ml-1 cursor-pointer">
              <span class="text-[14px] text-[#05192d] whitespace-nowrap leading-[30px] ml-4 mr-4">Aprenda</span>
            </a>
            <a class="hover:bg-[#dadadf] hover:rounded-full mt-1.5 mb-1.5 ml-1 mr-2 cursor-pointer">
              <span class="text-[14px] text-[#05192d] whitespace-nowrap leading-[30px] ml-4 mr-4">Instrutor</span>
            </a>
          </div>
        </div>
  
        <form action="{% url 'learn:courses' %}" method="GET" class="flex items-center">
          <label class="sr-only text-sm">Search</label>
            <div class="relative w-80">
                <div class="absolute inset-y-0 left-0 flex items-center pl-4 pointer-events-none">
                  <svg width="16" height="16" aria-hidden="true" viewBox="0 0 18 18" class=""><path fill="gray-800" d="m13.26 12.303 4.408 3.953a1 1 0 0 1-1.336 1.488L11.78 13.66a7.5 7.5 0 1 1 1.482-1.358ZM7.5 13a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z"></path></svg>
                </div>
                <input type="text" name="titulo" class="border-2 border-[#05192d26] text-[14px] rounded-full focus:ring-blue-50 focus:border-blue-500 block h-8 w-80 pl-10 p-3 outline-offset-0 focus:outline-none" placeholder="Search">
                <button hidden="True" type="submit"></button>
            </div> 
        </form>
  

      <div class="flex">
        <button id="dropdownDefaultButton" data-dropdown-toggle="dropdownNotification" class="relative inline-flex items-center text-sm font-medium text-center text-gray-700 hover:bg-gray-100 p-2 mr-4 rounded-full" type="button"> 
          <svg width="16" height="16" aria-hidden="true" viewBox="0 0 18 18"><path fill="currentColor" d="M10.995 2.14c2.764.494 3.874 2.202 4.71 5.79.67 2.877.983 4.081 1.537 5.32.501.423.752.984.758 1.725v.047C17.983 17.582 15.038 18 9 18c-6.035 0-8.98-.418-9-2.974v-.053c.006-.648.2-1.159.583-1.56a27.52 27.52 0 0 0 .916-2.778c.147-.534.278-1.064.428-1.71.039-.164.285-1.247.355-1.543.794-3.347 1.9-4.86 4.72-5.276a2 2 0 1 1 3.992.034Zm-1.75 1.845a2.02 2.02 0 0 1-.505-.002c-3.102.027-3.77.735-4.512 3.86-.068.286-.312 1.362-.353 1.535a45.228 45.228 0 0 1-.447 1.786c-.11.397-.224.787-.346 1.173C4.533 12.072 6.502 12 9 12c2.407 0 4.322.066 5.756.308-.293-.95-.581-2.134-.999-3.924-.804-3.449-1.541-4.345-4.512-4.399ZM9 16c3.866 0 7-.448 7-1s-3.134-1-7-1-7 .448-7 1 3.134 1 7 1Z"></path></svg>
        </button>
        
          <div id="dropdownNotification" class="hidden" 
            style="position: absolute;margin: 0px; padding: 8px 0px; outline: 0px; list-style: none; border-radius: 4px;
            box-shadow: rgba(5, 25, 45, 0.3) 0px 8px 12px -4px; top: 53px;background-color: rgb(255, 255, 255); 
            border: 1px solid rgba(5, 25, 45, 0.15); width: 340px;" aria-labelledby="dropdownNotificationButton">
            <div style="color: #05192d; font-size: 100%; font-weight: 400;line-height: 1.5;">

          <p class="mb-4 mt-2 text-sm text-center">Voce não possui notificações</p>
          <hr class="mb-2">

          <a style="background-color: rgba(5, 25, 45, 0.1); position: relative; display: inline-flex; -moz-box-align: center; align-items: center; -moz-box-pack: center;
            justify-content: center; flex-shrink: 0; vertical-align: middle; text-decoration: none; font-weight: 800; line-height: 1;
            margin: 0px 8px; margin-bottom: 7px; padding: 0px 16px; outline: 0px; border-style: solid; border-radius: 4px; border-width: 2px; user-select: none;
            cursor: pointer; height: 36px; min-width: 36px; flex-direction: column; font-size: 14px; color: rgb(5, 25, 45); background-color: transparent;
            border-color: rgba(5, 25, 45, 0.6); width: calc(100% - 16px);">
                Ver todas
          </a>
          </div>
        
      </div>

      <div class="relative">
        <button id="dropdownDefaultButton" data-dropdown-toggle="dropdownUser" class="flex items-center justify-end hover:bg-[#EFEFF5] rounded-full p-1">
          <div class="relative flex shrink-0 select-none items-center justify-center bg-[#0288D1] font-bold uppercase text-slate-800 h-6 w-6 text-xs rounded-full">
            <span class="text-white"></span>
          </div>
          <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
          </svg>
        </button>
      
        <div id="dropdownUser" class="absolute hidden">
          <div class="w-[240px] list-none m-0 py-4 bg-white border shadow">
            <div class="text-sm leading-6">
              <a class="relative flex items-center justify-center cursor-pointer rounded-md hover:bg-[#efeff5] px-3 ml-2 mr-2">
                <svg width="16" height="16" aria-hidden="true" viewBox="0 0 18 18"><path fill="currentColor" d="M7.186 15.621a3.047 3.047 0 0 1 3.628 0l.25.186a7.053 7.053 0 0 0 1.29-.535l.045-.308a3.047 3.047 0 0 1 2.565-2.565l.308-.046c.22-.41.4-.842.535-1.289l-.186-.25a3.047 3.047 0 0 1 0-3.628l.186-.25a7.053 7.053 0 0 0-.535-1.29l-.308-.045A3.047 3.047 0 0 1 12.4 3.036l-.046-.308c-.41-.22-.842-.4-1.289-.535l-.25.186a3.047 3.047 0 0 1-3.628 0l-.25-.186a7.053 7.053 0 0 0-1.29.535l-.045.308A3.047 3.047 0 0 1 3.036 5.6l-.308.046c-.22.41-.4.842-.535 1.289l.186.25a3.047 3.047 0 0 1 0 3.628l-.186.25c.136.447.315.879.535 1.29l.308.045A3.047 3.047 0 0 1 5.6 14.964l.046.308c.41.22.842.4 1.289.535l.25-.186ZM7.388 18a9.092 9.092 0 0 1-3.612-1.497l-.184-1.24a1.016 1.016 0 0 0-.856-.855l-1.24-.184A9.092 9.092 0 0 1 0 10.612l.747-1.007c.266-.36.266-.85 0-1.21L0 7.388a9.092 9.092 0 0 1 1.497-3.612l1.24-.184c.442-.066.789-.413.855-.856l.184-1.24A9.092 9.092 0 0 1 7.388 0l1.007.747c.36.266.85.266 1.21 0L10.612 0a9.092 9.092 0 0 1 3.612 1.497l.184 1.24c.066.442.413.789.856.855l1.24.184A9.092 9.092 0 0 1 18 7.388l-.747 1.007c-.266.36-.266.85 0 1.21L18 10.612a9.092 9.092 0 0 1-1.497 3.612l-1.24.184a1.016 1.016 0 0 0-.855.856l-.184 1.24A9.092 9.092 0 0 1 10.612 18l-1.007-.747a1.016 1.016 0 0 0-1.21 0L7.388 18ZM9 13.063a4.063 4.063 0 1 1 0-8.126 4.063 4.063 0 0 1 0 8.126Zm0-2.032A2.031 2.031 0 1 0 9 6.97a2.031 2.031 0 0 0 0 4.062Z"></path></svg>
                <span class="flex grow ml-2 pt-1.5 pb-1.5">
                  <span class="block overflow-hidden text-[14px] text-gray-800 leading-6">Configurações da conta</span>
                </span>
              </a>
              <div class="bg-[#efeff5] m-2" style="height: 1px;"></div>
              <a class="relative flex items-center justify-center cursor-pointer rounded-md hover:bg-[#efeff5] px-3 ml-2 mr-2">
                <svg width="14" height="14" aria-hidden="true" viewBox="0 0 18 18"><path fill="currentColor" d="M8 0a1 1 0 0 1 1 1v3.41a1 1 0 1 1-2 0V2H2v14h5v-2.428a1 1 0 1 1 2 0V17a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1a1 1 0 0 1 1-1h7Zm5.725 4.294 3.942 3.958a.997.997 0 0 1-.002 1.498l-3.956 3.957a1 1 0 0 1-1.497-1.322l.083-.094L14.58 10 5 10.002a1 1 0 1 1 0-2L14.593 8l-2.287-2.296a.998.998 0 0 1 .003-1.413 1.001 1.001 0 0 1 1.415.003Z"></path></svg>
                <span class="flex grow ml-2 pt-1.5 pb-1.5">
                  <span class="block overflow-hidden text-[14px] text-gray-800 leading-6">Log Out</span>
                </span>
              </a>
            </div>
          </div>
        </div>
      </div>
  </header>
</div>
    
<script>

var caminho_atual = window.location.pathname;
var div_nav = document.querySelector('#nav');
var links_navbar = div_nav.querySelectorAll('a');

links_navbar.forEach(function(link) {
  var caminho_link = link.getAttribute('href');

  if (caminho_atual.endsWith(caminho_link)) {
    link.classList.remove('hover:bg-[#dadadf]', 'hover:rounded-full');
    link.classList.add('bg-[#05192d]', 'rounded-full');
    var spans = link.querySelectorAll('span');
    spans.forEach(function(span) {
      span.classList.add('text-white', 'font-medium');
      span.classList.remove('text-[#05192d]');
    });
  }
});

</script>

learn/templates/partials/sidebar.html
<aside class="w-60 flex-none top-0 left-0 bg-[#000820;] px-6 py-20 overflow-y-auto border-r rtl:border-r-0 rtl:border-l dark:bg-gray-900 dark:border-gray-700" style="position: fixed; height: 100vh; font-family: 'Studio-Feixen' system-ui, -apple-system;">	
    <div class="flex flex-col justify-between flex-1">
        <nav class="-mx-2 space-y-5 ">
        <div>

            <a class="flex items-center px-1 py-2 text-white transition-colors duration-300 transform" href="{% url 'learn:progress' %}">
            <svg width="16" height="16" aria-hidden="true" viewBox="0 0 18 18"><path fill="currentColor" fill-rule="evenodd" clip-rule="evenodd" d="M13.2 13.932a3.654 3.654 0 0 0 1.032-3.109 25.039 25.039 0 0 1-.064-.478c1.717-1.966 3.3-5.07 3.451-7.952a1.827 1.827 0 0 0-1.92-1.92C12.825.624 9.727 2.202 7.764 3.91a18.361 18.361 0 0 1-.52-.065A3.654 3.654 0 0 0 4.17 4.882L2.882 6.171C.688 8.364.991 8.667 3.815 9.253l2.334.467c.283.522.588.952.929 1.293.342.342.771.646 1.294.929l.467 2.335c.546 2.784.888 3.127 3.082.933l1.279-1.278zM8.478 5.74c1.722-1.722 4.592-3.3 7.318-3.444-.143 2.726-1.722 5.596-3.444 7.318-.082.082-.058.573.073 1.472a1.824 1.824 0 0 1-.516 1.554l-1.279 1.279-.646-3.228c-.75-.319-1.288-.642-1.614-.969-.326-.326-.649-.864-.969-1.614l-3.228-.646 1.289-1.289a1.826 1.826 0 0 1 1.537-.518c.918.125 1.411.153 1.479.085zm4.505 1.413a1.37 1.37 0 1 1-1.937-1.936 1.37 1.37 0 0 1 1.937 1.936zM2.787 12.514a.1.1 0 0 0-.008.184l.281.132c.437.205.623.74.385 1.107l-.459.708c-.117.181.096.394.277.277l.708-.459c.367-.238.901-.052 1.107.385l.132.281a.1.1 0 0 0 .184-.008l.577-1.569c.691.322 1.02 1.12.757 1.835l-.636 1.728c-.215.584-1.063.536-1.351-.077l-.522-1.111-2.652 1.493c-.642.416-1.495-.437-1.078-1.079l1.493-2.653-1.111-.522c-.613-.288-.662-1.136-.077-1.351l1.728-.636a1.466 1.466 0 0 1 1.835.757l-1.57.578z"></path></svg>

            <span class="mx-2 text-[14px]">Progresso</span>
            </a>


            <a class="flex items-center px-1 py-2 text-[#b4bbc0] float-none transition-colors duration-300 transform dark:text-gray-200 hover:text-white " href="">
            <svg width="16" height="16" aria-hidden="true" viewBox="0 0 18 18"><path fill="currentColor" d="M4 0h10a2 2 0 0 1 2 2v14.828a1 1 0 0 1-1.65.76L8.988 13l-5.337 4.582A1 1 0 0 1 2 16.823V2a2 2 0 0 1 2-2Zm10 2H4v12.647l4.986-4.281L14 14.656V2Z"></path></svg>

            <span class="mx-2 text-[14px] leading-[17.5px]">Sua lista</span>
            </a>
        </div>            

        <div class="space-y-2 ">
            <label class="p-1 text-[0.70rem] font-normal tracking-wide text-white uppercase dark:text-gray-400">aprenda</label>

            <a class="flex items-center px-2 py-2 text-[#b4bbc0] font-normal transition-colors duration-300 transform dark:text-gray-200 hover:text-white " href="">
            <svg width="16" height="16" aria-hidden="true" viewBox="0 0 18 18"><path fill="currentColor" d="m13 6.3 3.331-2.998A1 1 0 0 1 18 4.045v9.91a1 1 0 0 1-1.669.743L13 11.7V14c0 .552-.485 1-1.083 1H1.083C.485 15 0 14.552 0 14V4c0-.552.485-1 1.083-1h10.834C12.515 3 13 3.448 13 4v2.3Zm0 2.69v.02l3 2.7V6.29l-3 2.7ZM2 5v8h9V5H2Z"></path></svg>
            <span class="mx-2 text-[14px]">Cursos</span>
            </a>

            <a class="flex items-center px-1 py-2 text-[#b4bbc0] transition-colors duration-300 transform dark:text-gray-200 hover:text-white " href="">
            <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 6.375c0 2.278-3.694 4.125-8.25 4.125S3.75 8.653 3.75 6.375m16.5 0c0-2.278-3.694-4.125-8.25-4.125S3.75 4.097 3.75 6.375m16.5 0v11.25c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125V6.375m16.5 0v3.75m-16.5-3.75v3.75m16.5 0v3.75C20.25 16.153 16.556 18 12 18s-8.25-1.847-8.25-4.125v-3.75m16.5 0c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125" />
            </svg>
            

            <span class="mx-2 text-[14px]">Data Science</span>
            </a>

            <a class="flex items-center px-1 py-2 text-[#b4bbc0] transition-colors duration-300 transform dark:text-gray-200 hover:text-white " href="">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
                <path d="M18.375 2.25c-1.035 0-1.875.84-1.875 1.875v15.75c0 1.035.84 1.875 1.875 1.875h.75c1.035 0 1.875-.84 1.875-1.875V4.125c0-1.036-.84-1.875-1.875-1.875h-.75zM9.75 8.625c0-1.036.84-1.875 1.875-1.875h.75c1.036 0 1.875.84 1.875 1.875v11.25c0 1.035-.84 1.875-1.875 1.875h-.75a1.875 1.875 0 01-1.875-1.875V8.625zM3 13.125c0-1.036.84-1.875 1.875-1.875h.75c1.036 0 1.875.84 1.875 1.875v6.75c0 1.035-.84 1.875-1.875 1.875h-.75A1.875 1.875 0 013 19.875v-6.75z" />
            </svg>
            
            <span class="mx-2 text-[14px]">Data Analysis</span>
            </a>

            <a class="flex items-center px-1 py-2 text-[#b4bbc0] transition-colors duration-300 transform dark:text-gray-200 hover:text-white " href="">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
            </svg>

            <span class="mx-2 text-[14px]">Web Development</span>
            </a>

            <a class="flex items-center px-1 py-2 text-[#b4bbc0] transition-colors duration-300 transform dark:text-gray-200 hover:text-white " href="">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
            </svg>

            <span class="mx-2 text-[14px]">Artificial Inteligence</span>
            </a>              
        </div>

        </nav>
    </div>
</aside>