core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from allauth.account import views
from accounts.views import CustomPasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')), 
    path("password/reset/", CustomPasswordResetView.as_view(), name="account_reset_password"),

    path("accounts/login/", views.login, name="account_reset_password_done"),

    path('users/', include('accounts.urls')),
    path('learn/', include('learn.urls')),
    path('', include('professores.urls', namespace="professores")),
    path('', include('cursos.urls')),    

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root= settings.MEDIA_ROOT
                          )

professores/urls.py
from django.urls import path
from . import views
from . import views_update


app_name = "professores"

urlpatterns = [
    path('area-do-professor', views.area_do_professor, name='area_do_professor'),
    path('adicionar-curso/', views.adicionar_curso, name='adicionar_curso'),
    path('adicionar-modulos/', views.adicionar_modulos, name='adicionar_modulos'),
    path('adicionar-video/aula/', views.adicionar_video_aula, name='adicionar_video_aula'),
    
    path('alteracoes-curso-<int:id>/', views_update.alterar_curso, name='editar_curso'),

    path('alteracoes-modulos/', views.modulos, name='modulos'),
    path('alteracoes-modulos-editar-<int:modulo_id>/', views_update.editar_modulo, name='editar_modulo'),

    path('alteracoes-aulas/', views.aulas, name='aulas'),
    path('alteracoes-aulas-editar-<int:aula_id>/', views_update.editar_aula, name='editar_aula'),
    
    path('excluir-curso-<int:id>/', views.excluir_curso, name='excluir_curso'),
    ]

professores/models.py
from django.db import models

professores/views.py
import os

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages 
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user
from django.core.paginator import Paginator
from cursos.models import Curso, Modulo, VideoAula
from django.shortcuts import get_object_or_404
from .tasks import upload
from django.conf import settings
from .filters import CursoFilter
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
from .status import HTTP_403_FORBIDDEN 


@login_required
def area_do_professor(request):
    instrutor = get_user(request)
    instrutor_cursos = instrutor.cursos.all().order_by('-created_at')
    status = request.GET.get('status')

    if not request.user.has_perm('accounts.acessar_area_do_professor'):
        return render(request, '403.html', status=HTTP_403_FORBIDDEN)
    
    if status:
        instrutor_cursos = instrutor_cursos.filter(status=status)
    
    cursos_filter = CursoFilter(request.GET, queryset=instrutor_cursos)
    
    if cursos_filter.is_valid():
        instrutor_cursos_filtrados = cursos_filter.qs
    else:
        instrutor_cursos_filtrados = instrutor_cursos

    paginator = Paginator(instrutor_cursos_filtrados, 4)
    numero_pagina = request.GET.get('page')
    cursos_pagina = paginator.get_page(numero_pagina)

    context = {
        'cursos_filter': cursos_filter.qs,
        'cursos': cursos_pagina,
        'instrutor_cursos': instrutor_cursos,
        'instrutor': instrutor,
        'status': status,
    }
    
    return render(request, 'area_do_professor.html', context)

@login_required
def modulos(request):
    id = request.session.get('id_curso')

    curso = get_object_or_404(Curso, id=id)
    modulos = curso.modulos.all()

    dados = {
        'curso': curso,
        'modulos': modulos,
    }

    return render(request, 'modulos.html', dados)

@login_required
def aulas(request):
    id = request.session.get('id_curso')
    
    curso = get_object_or_404(Curso, id=id)
    modulos = curso.modulos.all()
    aulas = VideoAula.objects.filter(modulo__in=modulos)

    dados = {
        'curso': curso,
        'modulos': modulos,
        'aulas': aulas
    }
    
    return render(request, 'aulas.html', dados)

@login_required
def adicionar_curso(request):
    if request.method == 'POST':
        dados = {
            'titulo': request.POST['titulo_curso'],
            'descricao': request.POST['descricao_curso'],
            'categoria': request.POST['categoria'],
            'nivel': request.POST.get('nivel'),
            'prerequisitos': request.POST.get('requisitos'),
            'professor': get_user(request)
        }

        request.session['dados_curso'] = dados

        try:
            curso = Curso(**dados)
            
            del request.session['dados_curso']
            
            curso.clean()
            curso.save()

            request.session['curso_id'] = curso.id
            return redirect('professores:adicionar_modulos')
        
        except ValidationError as e:
            messages.error(request, e.message)
            return redirect('professores:adicionar_curso')

    return render(request, 'novo_curso.html')

@login_required
def adicionar_modulos(request):
    curso_id = request.session.get('curso_id')
    curso = Curso.objects.get(id=curso_id)
    
    if request.method == 'POST':
        dados = {
            'titulo': request.POST['titulo_modulo'],
            'descricao': request.POST['descricao_modulo'],
            'curso': curso,
        }

        request.session['dados_modulos'] = dados

        try:
            modulo = Modulo(**dados)
            
            del request.session['dados_modulos']

            modulo.clean()
            modulo.save()

            request.session['modulo_id'] = modulo.id
            request.session['curso_id'] = modulo.curso_id

            return redirect('professores:adicionar_video_aula')

        except ValidationError as e:
            messages.error(request, e.message)

    return render(request, 'adicionar_modulos.html')

@login_required
def adicionar_video_aula(request):
    if request.method == 'POST':
        file = request.FILES.get('aula') 

        if file is not None:
            upload_dir = os.path.join(settings.MEDIA_ROOT, 'cursos', 'videos')
            destination = os.path.join(upload_dir, file.name)

            with open(destination, 'wb+') as destination_file:
                for chunk in file.chunks():
                    destination_file.write(chunk)

            file_path = os.path.join('cursos', 'videos', file.name)
            
            dados = {
                'titulo': request.POST['titulo_aula'],
                'descricao': request.POST['descricao_aula'],
            }
        
            request.session['dados_aulas'] = dados

            aula = VideoAula(**dados)
                
            del request.session['dados_aulas']

            request.session['video_aula_id'] = aula.id
            modulo_id = request.session['modulo_id']
            
            modulo = Modulo.objects.get(id=modulo_id)
            aula.modulo = modulo
            aula.save()

            upload(aula.id, file_path) 
                    
        else: 
            return render(request, 'adicionar_video_aula.html')

    if 'dados_modulos' in request.session:
        dados_modulos = request.session['dados_modulos']

    else:
        dados_modulos = {}

    modulos = Modulo.objects.filter(**dados_modulos)

    context = {
        'modulos': modulos,
    }

    return render(request, 'adicionar_video_aula.html', context)

@login_required
def alterar_curso(request, id):
    curso = get_object_or_404(Curso, id=id)
    
    request.session['id_curso'] = curso.id

    if request.method == 'POST':
        if 'nova_categoria' in request.POST:
            curso.categoria = request.POST.get('nova_categoria')
            
        curso.titulo =  request.POST.get('novo_titulo')
        curso.descricao = request.POST.get('nova_descricao')
        curso.nivel = request.POST.get('novo_nivel')
        curso.prerequisitos = request.POST.get('novos_requisitos')
     
        try:
            curso.save()

        except ValidationError as e:
            messages.error(request, e.message)

    dados = {'curso': curso}
    template = 'curso.html'

    return render(request, template, dados)

@login_required
def editar_modulo(request, modulo_id):
    modulo = get_object_or_404(Modulo, id=modulo_id)
    curso_id = modulo.curso.id

    if request.method == 'POST':
        modulo.titulo = request.POST.get('novo_titulo_modulo')
        modulo.descricao = request.POST.get('nova_descricao_modulo')

        modulo.save()
        
        return HttpResponseRedirect(reverse('professores:modulos'))
    
    dados = {'modulo': modulo}
    template = 'modulos.html'
    
    return render(request, template, dados)

@login_required
def editar_aula(request, aula_id):
    aula = get_object_or_404(VideoAula, id=aula_id)

    if request.method == 'POST':
        aula.titulo = request.POST.get('novo_titulo_aula')
        aula.descricao = request.POST.get('nova_descricao_aula')

        file = request.FILES.get('novo_video_aula')

        if file:
            upload_dir = os.path.join(settings.MEDIA_ROOT, 'cursos', 'videos')
            file_path = os.path.join(upload_dir, file.name)

            with open(file_path, 'wb+') as destino_file:
                for chunk in file.chunks():
                    destino_file.write(chunk)

            aula.video.name = os.path.join('cursos', 'videos', file.name)

        aula.save()

        return HttpResponseRedirect(reverse('professores:aulas'))

    dados = {'aula': aula}
    template = 'aulas.html'

    return render(request, template, dados)

@login_required
def excluir_curso(request, id):
    curso = get_object_or_404(Curso, id=id)
    curso.delete()

    return redirect('professores:area_do_professor')

@login_required
def realizar_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('logar'))

professores/templates/base/menu_de_edicao.html
<aside class=" flex flex-col w-60 h-100 px-5 py-8">

    <ul>
     <a class="block py-0.5 text-sm font-medium leading-6 text-slate-700 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-300">Crie seu curso</a>  

      <ul>
        <li>
          <ul>
            <li class="ml-4 ">
              <a href="{% url 'professores:editar_curso' curso.id %}" class="group flex items-start gap-x-2 py-0.5 text-sm text-gray-700 leading-6 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300 hs-scrollspy-active:text-blue-600 dark:hs-scrollspy-active:text-blue-400">
                <svg class="w-2 h-6 text-gray-400 overflow-visible group-hover:text-gray-600 dark:text-gray-600 dark:group-hover:text-gray-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M5 2L10.6464 7.64645C10.8417 7.84171 10.8417 8.15829 10.6464 8.35355L5 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                </svg>
                Informações iniciais
              </a>
            </li>
            <ul>

          <a class="block py-0.5 mt-2 text-sm font-medium leading-6 text-slate-700 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-300">Módulos</a>  
      
            <ul class="sticky top-0" >
              <li>
                <ul>
                  <li class="ml-4">
                    <a href="{% url 'professores:modulos' %}" class="group flex items-start gap-x-2 py-0.5 text-sm text-gray-700 leading-6 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300 hs-scrollspy-active:text-blue-600 dark:hs-scrollspy-active:text-blue-400">
                      <svg class="w-2 h-6 text-gray-400 overflow-visible group-hover:text-gray-600 dark:text-gray-600 dark:group-hover:text-gray-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5 2L10.6464 7.64645C10.8417 7.84171 10.8417 8.15829 10.6464 8.35355L5 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                      </svg>
                      Seções do curso
                    </a>
                </li>
                
          <a class="block py-0.5 mt-2 text-sm font-medium leading-6 text-slate-700 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-300">Aulas</a>  
      
          <ul class="sticky top-0" >
            <li>
              <ul>
                <li class="ml-4">
                  <a href="{% url 'professores:aulas' %}" class="group flex items-start gap-x-2 py-0.5 text-sm text-gray-700 leading-6 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300 hs-scrollspy-active:text-blue-600 dark:hs-scrollspy-active:text-blue-400">
                    <svg class="w-2 h-6 text-gray-400 overflow-visible group-hover:text-gray-600 dark:text-gray-600 dark:group-hover:text-gray-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M5 2L10.6464 7.64645C10.8417 7.84171 10.8417 8.15829 10.6464 8.35355L5 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                    </svg>
                    Upload de arquivos
                  </a>
              </li>  
  </aside>

professores/templates/base/menu_etapas.html
<aside class=" flex flex-col w-60 h-100 px-5 py-8">

    <ul>
     <a class="block py-0.5 text-sm font-medium leading-6 text-slate-700 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-300">Crie seu curso</a>  

      <ul>
        <li>
          <ul>
            <li class="ml-4 ">
              <a href="{% url 'professores:adicionar_curso' %}" class="group flex items-start gap-x-2 py-0.5 text-sm text-gray-700 leading-6 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300 hs-scrollspy-active:text-blue-600 dark:hs-scrollspy-active:text-blue-400">
                <svg class="w-2 h-6 text-gray-400 overflow-visible group-hover:text-gray-600 dark:text-gray-600 dark:group-hover:text-gray-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M5 2L10.6464 7.64645C10.8417 7.84171 10.8417 8.15829 10.6464 8.35355L5 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                </svg>
                Informações iniciais
              </a>
            </li>
            <ul>

          <a class="block py-0.5 mt-2 text-sm font-medium leading-6 text-slate-700 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-300">Módulos</a>  
      
            <ul class="sticky top-0" >
              <li>
                <ul>
                  <li class="ml-4">
                    <a href="{% url 'professores:adicionar_modulos' %}" class="group flex items-start gap-x-2 py-0.5 text-sm text-gray-700 leading-6 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300 hs-scrollspy-active:text-blue-600 dark:hs-scrollspy-active:text-blue-400">
                      <svg class="w-2 h-6 text-gray-400 overflow-visible group-hover:text-gray-600 dark:text-gray-600 dark:group-hover:text-gray-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5 2L10.6464 7.64645C10.8417 7.84171 10.8417 8.15829 10.6464 8.35355L5 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                      </svg>
                      Seções do curso
                    </a>
                </li>
                
          <a class="block py-0.5 mt-2 text-sm font-medium leading-6 text-slate-700 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-300">Aulas</a>  
      
          <ul class="sticky top-0" >
            <li>
              <ul>
                <li class="ml-4">
                  <a href="{% url 'professores:adicionar_video_aula' %}" class="group flex items-start gap-x-2 py-0.5 text-sm text-gray-700 leading-6 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300 hs-scrollspy-active:text-blue-600 dark:hs-scrollspy-active:text-blue-400">
                    <svg class="w-2 h-6 text-gray-400 overflow-visible group-hover:text-gray-600 dark:text-gray-600 dark:group-hover:text-gray-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M5 2L10.6464 7.64645C10.8417 7.84171 10.8417 8.15829 10.6464 8.35355L5 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                    </svg>
                    Upload de arquivos
                  </a>
              </li>  
  </aside>